version: '3'
services:
  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8070:8070"
    restart: always
  eureka-server:
    image: eureka-server
    hostname: localhost
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8761:8761"
  products:
    image: products
    build:
      context: ./products
      dockerfile: Dockerfile
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    ports:
      - "8080:8080"
  orders:
    image: orders
    build:
      context: ./orders
      dockerfile: Dockerfile
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    ports:
      - "8081:8081"

networks:
  default: