apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: madaamn/config-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: madaamn/eureka-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: madaamn/products
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: madaamn/orders
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
      imagePullSecrets:
        - name: regcred